name: MOOSE Master

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '30 5 * * 5'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v4
    - name: Activate MOOSE environment
      uses: conda-incubator/setup-miniconda@main
      with:
        python-version: '3.10'
        mamba-version: "*"
        channels: https://conda.software.inl.gov/public,conda-forge,defaults
        channel-priority: true
        miniforge-variant: Miniforge3
        miniforge-version: latest
        activate-environment: moose
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda init
        conda activate moose
        conda install moose-dev
    - name: Install MOOSE
      shell: bash -l {0}
      run: |
        cd ..
        git clone https://github.com/idaholab/moose.git
        cd moose
        git checkout master
        conda activate moose
        cd test
        make -j4
#    - name: Run MOOSE Tests
#      shell: bash -l {0}
#      run: |
#        conda activate moose
#        cd ..
#        cd moose/test
#        ./run_tests -j4
    - name: Build CATS
      shell: bash -l {0}
      run: |
        conda activate moose
        make -j4
    - name: Run CATS Tests
      shell: bash -l {0}
      run: |
        conda activate moose
        ./run_tests -j4
